---
title: "Grade analysis"
author: "Ghina Mezher"
format: html
---

```{r message=FALSE}
here::i_am("r-101-grade-analysis.Rproj")
library(here)
library(ggplot2)
library(dplyr)
library(vroom)
library(tidyr)
```

## Question 1
```{r message=FALSE}
df<-vroom(here("grades.csv"))
na.rm=TRUE
```
## Question 2
```{r}
df|>
  summarise("Minimum"=min(`Exam`,na.rm=TRUE),"Maximum"=max(`Exam`,na.rm=TRUE),"Median"=median(`Exam`,na.rm=TRUE),"Mean"=mean(`Exam`,na.rm=TRUE))|>
  knitr::kable()
```
## Question 3
```{r}
sum(is.na(df$Exam))
```
`r sum(is.na(data$Exam)` students who did not pass the final exam is. 

## Question 4
```{r}
df|>ggplot(aes(x=Exam))+
  geom_histogram(binwidth=2,fill="darkred",color="red",na.rm=TRUE)+
  labs(title= "Distribution of Exam grades",
       x="Grades to the final exam",
      y="Frequency of grades")
```


## Question 5
```{r}
group_counts<-df|>
  group_by(Group)|>
  summarise(Number=n())

knitr::kable(group_counts)
```
## Question 6
```{r}
ggplot(group_counts,aes(x=Group,y=Number))+
  geom_col(fill="darkblue")+
  labs(title="Number of students per group",x="Groups",y="Number of students")
```
## Question 7
```{r}
#first option
ggplot(df,aes(x=Exam, color=Group))+
  geom_density()



#Second option
ggplot(df,aes(x=Group, y=Exam))+
  geom_boxplot(fill="darkgreen")+
  labs(title="Distribution of grades to the final exam according to groups",x="Groups",y="Grades to the final exam")+
  coord_flip()
```
The first graphical representation to be criticized.

## Question 8
```{r}
na_grades<-df|>
  group_by(Group)|>
  summarise("Number of students missing"=sum(is.na(Exam)))

na_grades
```
## Question 9
```{r}
ggplot(na_grades,aes(x=Group,y=`Number of students missing`))+
  geom_col(fill="purple")+
  labs(title="Missing students to the final exam by group", x="Groups",y="Number of missing students")+
  coord_flip()
```
## Question 10
```{r}
reshape_df<-df|>pivot_longer(cols=-c(Id,Group))
```

#Question 11
```{r}
NA_count<-reshape_df|>
  group_by(Id)|>
  summarise("Missing grades"=sum(is.na(value)))

knitr::kable(NA_count)
```
## Question 12
```{r}

```


